export const SampleSysuserData = [
	{
		'id': 1,
		'name': 'Test Manager',
		'email': 'test1@intelliwake.com',
		'smsphone': '',
		'features': [],
		'title': '',
		'is_active': true,
		'is_admin': true,
		'is_sysadmin': true,
		'hire_date': null,
		'terminated_date': null,
		'is_non_exempt': null,
		'manager_sysuser_id': null,
		'default_timecard_activity_id': null,
		'default_project_id': 24,
		'employee_nbr': null,
		'secondary_project_id': null,
		'updated_ts': '2022-12-20 23:35:54.261-05'
	},
	{
		'id': 2,
		'name': 'Test Subordinate',
		'email': 'test2@intelliwake.com',
		'smsphone': '',
		'features': ['TimesheetAdmin', 'Payroll', 'UserAdmin'],
		'title': '',
		'is_active': true,
		'is_admin': false,
		'is_sysadmin': false,
		'hire_date': '2022-10-19',
		'terminated_date': null,
		'is_non_exempt': true,
		'manager_sysuser_id': 1,
		'default_timecard_activity_id': null,
		'default_project_id': 10,
		'employee_nbr': null,
		'secondary_project_id': null,
		'updated_ts': '2022-10-19 12:52:11.004-04'
	},
	{
		'id': 3,
		'name': 'Test Manager2',
		'email': 'test3@intelliwake.com',
		'smsphone': '',
		'features': [],
		'title': '',
		'is_active': true,
		'is_admin': true,
		'is_sysadmin': true,
		'hire_date': null,
		'terminated_date': null,
		'is_non_exempt': null,
		'manager_sysuser_id': null,
		'default_timecard_activity_id': null,
		'default_project_id': 24,
		'employee_nbr': null,
		'secondary_project_id': null,
		'updated_ts': '2022-12-20 23:35:54.261-05'
	},
	{
		'id': 4,
		'name': 'Test Subordinate2',
		'email': 'test4@intelliwake.com',
		'smsphone': '',
		'features': ['TimesheetAdmin', 'Payroll', 'UserAdmin'],
		'title': '',
		'is_active': false,
		'is_admin': false,
		'is_sysadmin': false,
		'hire_date': '2022-10-19',
		'terminated_date': null,
		'is_non_exempt': true,
		'manager_sysuser_id': 3,
		'default_timecard_activity_id': null,
		'default_project_id': 10,
		'employee_nbr': null,
		'secondary_project_id': null,
		'updated_ts': '2022-10-19 12:52:11.004-04'
	}
]
